/* C source generated by Harbour */

#include "hbvmpub.h"
#include "hbinit.h"

HB_FUNC( ICOR );
HB_FUNC_EXTERN( SETCOLOR );

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_ICOR )
{ "ICOR", { HB_FS_PUBLIC | HB_FS_FIRST | HB_FS_LOCAL }, { HB_FUNCNAME( ICOR ) }, NULL },
{ "SETCOLOR", { HB_FS_PUBLIC }, { HB_FUNCNAME( SETCOLOR ) }, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_ICOR, "", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_ICOR
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_ICOR )
   #include "hbiniseg.h"
#endif

HB_FUNC( ICOR )
{
	static const HB_BYTE pcode[] =
	{
		36,1,0,176,1,0,106,5,114,43,47,82,0,20,1,7
	};

	hb_vmExecute( pcode, symbols );
}
