/* C source generated by Harbour */

#include "hbvmpub.h"
#include "hbinit.h"

HB_FUNC( TEMP );
HB_FUNC_EXTERN( DBUSEAREA );
HB_FUNC_EXTERN( DBAPPEND );
HB_FUNC_EXTERN( STRZERO );

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_TEMP )
{ "TEMP", { HB_FS_PUBLIC | HB_FS_FIRST | HB_FS_LOCAL }, { HB_FUNCNAME( TEMP ) }, NULL },
{ "DBUSEAREA", { HB_FS_PUBLIC }, { HB_FUNCNAME( DBUSEAREA ) }, NULL },
{ "I", { HB_FS_PUBLIC | HB_FS_MEMVAR }, { NULL }, NULL },
{ "DBAPPEND", { HB_FS_PUBLIC }, { HB_FUNCNAME( DBAPPEND ) }, NULL },
{ "STRZERO", { HB_FS_PUBLIC }, { HB_FUNCNAME( STRZERO ) }, NULL },
{ "USUARIO", { HB_FS_PUBLIC }, { NULL }, NULL },
{ "CODUSU", { HB_FS_PUBLIC | HB_FS_MEMVAR }, { NULL }, NULL },
{ "FANTAZIA", { HB_FS_PUBLIC | HB_FS_MEMVAR }, { NULL }, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_TEMP, "", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_TEMP
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_TEMP )
   #include "hbiniseg.h"
#endif

HB_FUNC( TEMP )
{
	static const HB_BYTE pcode[] =
	{
		36,1,0,176,1,0,120,100,106,8,117,115,117,97,114,105,111,0,100,
		100,9,20,6,36,2,0,122,165,83,2,0,25,55,36,3,0,176,3,
		0,20,0,36,4,0,176,4,0,109,2,0,92,4,12,2,108,5,76,
		6,36,5,0,176,4,0,109,2,0,92,4,12,2,108,5,76,7,36,
		2,0,109,2,0,23,21,83,2,0,93,15,39,15,28,199,36,6,0,
		7
	};

	hb_vmExecute( pcode, symbols );
}
