/* C source generated by Harbour */

#include "hbvmpub.h"
#include "hbinit.h"

HB_FUNC( MAIN );
HB_FUNC_EXTERN( QOUT );

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_TESTE )
{ "MAIN", { HB_FS_PUBLIC | HB_FS_FIRST | HB_FS_LOCAL }, { HB_FUNCNAME( MAIN ) }, NULL },
{ "QOUT", { HB_FS_PUBLIC }, { HB_FUNCNAME( QOUT ) }, NULL },
{ "EVAL", { HB_FS_PUBLIC | HB_FS_MESSAGE }, { NULL }, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_TESTE, "", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_TESTE
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_TESTE )
   #include "hbiniseg.h"
#endif

HB_FUNC( MAIN )
{
	static const HB_BYTE pcode[] =
	{
		36,2,0,176,1,0,48,2,0,89,10,0,1,0,0,0,95,1,6,
		106,2,65,0,106,2,66,0,112,2,20,1,36,3,0,176,1,0,48,
		2,0,89,13,0,2,0,0,0,95,1,95,2,72,6,106,2,65,0,
		106,2,66,0,112,2,20,1,36,4,0,176,1,0,48,2,0,89,10,
		0,3,0,0,0,95,1,6,106,2,65,0,106,2,66,0,112,2,20,
		1,36,5,0,7
	};

	hb_vmExecute( pcode, symbols );
}
